name: AWS


env:
  IMAGE_NAME: semicohete/api-gonzalezdominguez
  # FILES: compose.yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



jobs:
  deploy:
    name: deploy en AWS
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USER_EC2 }}
          key: ${{ secrets.CLAVE_EC2 }}
          ip: ${{ secrets.IP_EC2 }}
          port: 22 # ${{ secrets.PORT }}
          script: |
            docker rm -f api-gonzalezdominguez
            docker rmi ${{ env.IMAGE_NAME }}
            docker run -d -p 80:5000 --name api-gonzalezdominguez ${{ env.IMAGE_NAME }}