name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.TOKEN_DH }}" | docker login -u "${{ secrets.USER_DH }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.USER_DH }}/api-gonzalezdominguez:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.USER_DH }}/api-gonzalezdominguez:latest

    - name: Copiar la SSH key
      run: |
        echo "${{ secrets.CLAVE_EC2 }}" > clave_ec2.pem
        chmod 600 clave_ec2.pem

    - name: Lanzamos EC2 via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i clave_ec2.pem ${{ secrets.USER_EC2 }}@${{ secrets.IP_EC2 }} << 'EOF'
          docker pull ${{ secrets.USER_DH }}/api-gonzalezdominguez:latest
          docker stop api-gonzalezdominguez || true && docker rm api-gonzalezdominguez || true
          docker run -d --name api-gonzalezdominguez -p 80:80 ${{ secrets.USER_DH }}/api-gonzalezdominguez:latest
        EOF
