name: CI/CD completo

env:
  IMAGE_NAME: galeria
  # FILES: compose.yml

# GitHub Secrets
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
# AWS_HOSTNAME
# AWS_USERNAME
# AWS_PRIVATEKEY

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    # se comenta para no interferir en protección de ramas
    # paths:
    #   - '**.py'

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=79 --statistics

  build_and_push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

  deploy:
    name: deploy en AWS
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATEKEY }}
          port: 22 # ${{ secrets.PORT }}
          script: |
            sleep 30
            docker rm -f web1
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
            docker run -d -p 80:5000 --name web1 ${{secrets.DOCKERHUB_USERNAME}}/${{env.IMAGE_NAME}}