name: AWS + DockerHub

env:
  IMAGE_NAME: api-gonzalezdominguez
  # FILES: compose.yml

# GitHub Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    # se comenta para no interferir en protección de ramas
    # paths:
    #   - '**.py'

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_DH }}
          password: ${{ secrets.TOKEN_DH }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.USER_DH }}/${{ env.IMAGE_NAME }}

  deploy:
    name: deploy en AWS
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_EC2 }}
          username: ${{ secrets.USER_EC2 }}
          key: ${{ secrets.CLAVE_EC2 }}
          port: 22 # ${{ secrets.PORT }}
          script: |
            sleep 30
            docker rm -f api-gonzalezdominguez
            docker rmi ${{ secrets.USER_DH }}/${{ env.IMAGE_NAME }}
            docker run -d -p 80:5000 --name api-gonzalezdominguez ${{secrets.USER_DH}}/${{env.IMAGE_NAME}}